sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "5.1.0"
before_install:
  - npm i -g npm@^3.0.0
  - npm i -g firebase-tools
before_script:
  - npm prune
script:
  - npm run build
after_success:
  - firebase deploy --token ${FIREBASE_TOKEN}