sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- 5.1.0
before_install:
- npm i -g npm@^3.0.0
- npm i -g firebase-tools
before_script:
- npm prune
script:
- npm run build
after_success:
- firebase deploy --token ${FIREBASE_TOKEN} --project ${FIREBASE_PROJECT}
- cd dist
deploy:
  provider: heroku
  api_key:
    secure: I79aBY0NNpeVp1dxqXE32VYQ7fuBQW+Tn3Q1az6S9oFkUphoJuUB85RLNp8E6qjcQ3opiooSH9L/4ILYWmShOQpeAqmkaH529Ia6YS0W8VrFA1wN/3Nr/xc6PGE5wOl1s1DIeqMYKlqbT2s/pBXYqIHfJFnzyVgV9RcYI1wdo5lY6+h0XCsv9IIqBkRZjM06nolE+c/tr/m5K5RfTAj5h0I5gF0ogAuGK+EjEzfxDDsXWFNqINpefTeQav+BiJQsmeV8SM1ZAEJsmeygRGXRlaH8cUVp3CzKsOq8oXmvQFn/Aa0zpZeb6GleJTrTk3cN/1hbRRFILVJNac/gqJ4JgRa1U06mInDX4jcqEIb8P4AH8PxSWCnhe1wJ9mRJKqLDr1QDO+Mz5l7cy7wZsYrRgstT8e0No0BfXAJVv7bwM1XD9opflmk39KZDq4xIGBPUmUnqgUMLDqtqAHjO7KQnBEIEvNm9ul2srQkuAl53bdd9AzdnLy0qcJk80M09YjResSfUggb7KCLekINChTEk5mQiFvoIc66Nr6awC1xA/bOIyZ2EANvOrevXIcZNM4s9adAoP8zBTAEsSA4nEbVHNhL312uG/yKlMTETaWwq2K2NcYc75kqrSGMVanWsYl2o/XKfPJvMs9fnV0+Q4a3aKRJkITAaxp3rD3WxPoWzky4=
    app: thebigfatninja-homepage
notifications:
  email:
    on_failure: always
